version: "3"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  api:
    image: ghcr.io/kma-live-tv/api:latest
    restart: always
    ports:
      - "8088:8088"
    environment:
      DB_URL: "jdbc:postgresql://db:5432/livetv"
      DB_USER: "postgres"
      DB_PASSWORD: "${DB_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRATION: "${JWT_EXPIRATION}"
      SRS_API_URL: "${SRS_API_URL}"
      STRIPE_SECRET: "${STRIPE_SECRET}"
      STRIPE_ENDPOINT_SECRET: "${STRIPE_ENDPOINT_SECRET}"

  srs:
    image: ossrs/srs:4
    restart: always
    command: ./objs/srs -c conf/srs.conf
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8080:8080"
    volumes:
      - "./srs.conf:/usr/local/srs/conf/srs.conf"
      - srs-objs:/usr/local/srs/objs

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"

volumes:
  db:
  srs-objs:
