CREATE TABLE comments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    livestream_id BIGINT                                  NOT NULL,
    content       VARCHAR(255),
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE livestreams
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    stream_key VARCHAR(255),
    dvr_file   VARCHAR(255),
    status     VARCHAR(255),
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_livestreams PRIMARY KEY (id)
);

CREATE TABLE reactions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    livestream_id BIGINT                                  NOT NULL,
    type          VARCHAR(255),
    user_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_reactions PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    username     VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    display_name VARCHAR(255)                            NOT NULL,
    balance      BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE livestreams
    ADD CONSTRAINT uc_livestreams_dvrfile UNIQUE (dvr_file);

ALTER TABLE livestreams
    ADD CONSTRAINT uc_livestreams_streamkey UNIQUE (stream_key);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_LIVESTREAM FOREIGN KEY (livestream_id) REFERENCES livestreams (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE livestreams
    ADD CONSTRAINT FK_LIVESTREAMS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE reactions
    ADD CONSTRAINT FK_REACTIONS_ON_LIVESTREAM FOREIGN KEY (livestream_id) REFERENCES livestreams (id);

ALTER TABLE reactions
    ADD CONSTRAINT FK_REACTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);