CREATE TABLE notifications
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    content       VARCHAR(255)                            NOT NULL,
    livestream_id BIGINT,
    user_id       BIGINT,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

ALTER TABLE livestreams
    ADD content VARCHAR(255);
